version: '3'
services:
  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_USER: 'sharedvalue_admin'
      POSTGRES_PASSWORD: 'admin_Aa123'
      POSTGRES_DB: 'shared_value'
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  haproxy:
    image: haproxy:1.9-alpine
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
volumes:
  postgresql-data:
